name = Angel
description = A custom layout for Los Angeles Web Design.
preview = preview.png
template = angel-layout

; Regions
regions[branding]       = Branding
regions[header]         = Header
regions[navigation]     = Navigation bar
regions[highlighted]    = Highlighted
regions[help]           = Help
regions[content]        = Content
;regions[sidebar_first]  = First sidebar
;regions[sidebar_second] = Second sidebar
regions[footer]         = Footer

; Stylesheets
stylesheets[all][] = css/layouts/angel/angel.layout.css
stylesheets[all][] = css/layouts/angel/angel.layout.no-query.css
